version: 1
project:
  name: dodo
  description: The dodo documentation
  version: 0.0.1
pages:
  - markdown: docs/quick_start.md
    path: "what_is_dodo"
    title: "What is dodo?"
  - markdown: docs/install.md
    path: "install"
    title: "Install"
  - markdown: docs/quick_start.md
    path: "quick_start"
    title: "Quick Start"
  - markdown: docs/yaml_spec.md
    path: "yaml_specification"
    title: "Yaml Spec"
  - markdown: docs/cicd.md
    path: "cicd"
    title: "Use with CI/CD"
  - markdown: docs/roadmap.md
    path: "roadmap"
    title: "Roadmap"
 