version: 1
project:
  name: dodo
  description: test project
  version: 0.0.1
pages:
  - filepath: docs/index.md
    path: "/test"
    title: "What is dodo"
  - match: "docs/*.md"
    title: "test"
  - filepath: docs/index.md
    path: "/directory"
    title: "ok"
    children:
      - match: docs/usage/*.md
        title: "test2"
 
