version: 1
project:
  name: dodo
  description: The dodo documentation
  version: 0.0.1
index:
  title: "test"
  filepath: docs/index.md
pages:
  - filepath: docs/install.md
    path: "install"
    title: "Install"
  - filepath: docs/quick_start.md
    path: "quick_start"
    title: "Quick Start"
  - filepath: docs/yaml_specification.md
    path: "yaml_specification"
    title: "Yaml Spec"
 
 
