version: 1
project:
  project_id: "document"
  name: dodo
  description: The dodo documentation
  version: 0.0.28
pages:
  - markdown: docs/index.md
    path: "what_is_dodo"
    title: "What is dodo?"
  - markdown: docs/install.md
    path: "install"
    title: "Install"
  - markdown: docs/quick_start.md
    path: "quick_start"
    title: "Quick Start"
  - markdown: docs/yaml_spec.md
    path: "yaml_specification"
    title: "Yaml Spec"
  - markdown: docs/markdown_syntax.md
    path: "markdown"
    title: "Markdown Syntax"
  - directory: "Work with CI/CD"
    children:
      - markdown: docs/cicd_github.md
        path: "cicd_github"
        title: "GitHub Actions"
  - directory: "CLI Commands"
    children:
      - markdown: docs/command_init.md
      - markdown: docs/command_upload.md
      - markdown: docs/command_preview.md
      - markdown: docs/command_check.md
      - markdown: docs/command_touch.md
      - markdown: docs/command_read.md
      - markdown: docs/command_mcp.md
  - markdown: docs/release_note.md
    path: "release_note"
    title: "Release Note"
  - markdown: docs/roadmap.md
    path: "roadmap"
    title: "Roadmap"
  - directory: "For Developers"
    children:
      - markdown: docs/for_contributors/getting_started.md
      - markdown: docs/for_contributors/guidelines.md
      - markdown: docs/for_contributors/release.md
 