version: 1
project:
  name: dodo
  description: The dodo documentation
  version: 0.0.1
pages:
  - markdown: docs/index.md
    path: "what_is_dodo"
    title: "What is dodo?"
  - markdown: docs/install.md
    path: "install"
    title: "Install"
  - markdown: docs/quick_start.md
    path: "quick_start"
    title: "Quick Start"
  - markdown: docs/yaml_spec.md
    path: "yaml_specification"
    title: "Yaml Spec"
  - markdown: docs/markdown_syntax.md
    path: "markdown"
    title: "Markdown Syntax"
  - directory: "Work with CI/CD"
    children:
      - markdown: docs/cicd_github.md
        path: "cicd_github"
        title: "GitHub Actions"
  - markdown: docs/roadmap.md
    path: "roadmap"
    title: "Roadmap"
  - markdown: docs/release_note.md
    path: "release_note"
    title: "Release Note"
  - directory: "For Developers"
    children:
      - markdown: docs/internal/release.md
        path: "release_flow"
        title: "Release Flow"
 