version: 1
project:
  project_id: "document"
  name: dodo
  description: The dodo documentation
  version: 0.0.29
pages:
  - markdown: docs/index.md
  - markdown: docs/install.md
  - markdown: docs/quick_start.md
  - markdown: docs/cicd_github.md
  - markdown: docs/yaml_spec.md
  - markdown: docs/markdown_syntax.md
  - markdown: docs/upload_image.md
  - directory: "CLI Commands"
    children:
      - markdown: docs/command_init.md
      - markdown: docs/command_upload.md
      - markdown: docs/command_preview.md
      - markdown: docs/command_check.md
      - markdown: docs/command_touch.md
      - markdown: docs/command_read.md
      - markdown: docs/command_mcp.md
  - markdown: docs/release_note.md
  - markdown: docs/roadmap.md
  - directory: "For Developers"
    children:
      - markdown: docs/for_contributors/getting_started.md
      - markdown: docs/for_contributors/guidelines.md
      - markdown: docs/for_contributors/release.md
assets:
  - "assets/**"
 