linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    # - deadcode  # Deprecated
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    # - execinquery  # Deprecated
    - exhaustive
    # - exhaustivestruct
    # - exhaustruct
    # - exportloopref  # Deprecated
    - forbidigo
    # - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox
    # - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    # - golint  # Deprecated
    # - gomnd
    # - gomoddirectives
    - gomodguard
    - goprintffuncname
    # - gosec  # Too many false positives
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    # - ifshort
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    # - interfacer  # Deprecated
    - ireturn
    # - lll
    - loggercheck
    - maintidx
    - makezero
    # - maligned  # Deprecated
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    # - nlreturn
    # - noctx
    - nolintlint
    - nonamedreturns
    # - nosnakecase
    - nosprintfhostport
    # - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    # - scopelint  # Deprecated
    - sloglint
    - sqlclosecheck
    - staticcheck
    # - structcheck  # Deprecated
    - stylecheck
    - tagalign
    # - tagliatelle
    # - tenv  # Deprecated
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varcheck  # Deprecated
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl
    - zerologlint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen