name: preview-document
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pull-requests: write
jobs: 
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dodo CLI
        run: |
          npm install -g @dodo-doc/cli
      - name: Preview docs
        id: preview
        continue-on-error: true
        run: |
          dodo preview --format json 1> stdout.txt 2> stderr.txt
        env:
          DODO_API_KEY: ${{ secrets.DODO_ACCESS_KEY }}
      - name: Prepare comment body
        id: prepare-comment
        run: |
          STATUS=$(jq -r '.status' stdout.txt 2>/dev/null || echo "false")
          URL=$(jq -r '.document_url' stdout.txt 2>/dev/null || echo "")
      
          if [ "$STATUS" = "false" ] || [ -z "$URL" ]; then
            echo "failed"
            echo "status=failed" >> $GITHUB_OUTPUT

            # Build comment body
            echo "❌ Document preview failed" >> body.txt
            echo "<details><summary>Error Message</summary>" >> body.txt
            echo "<pre><code>" >> body.txt
            cat stderr.txt >> body.txt
            echo "</code></pre>" >> body.txt
            echo "</details>" >> body.txt

          else
            echo "success"
            echo "status=success" >> $GITHUB_OUTPUT

            # Build comment body
            echo "✅ Document preview is available [here]($URL)" >> body.txt
          fi
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: body.txt
      - name: Fail if preview failed
        if: steps.prepare-comment.outputs.status == 'failed'
        run: exit 1
