name: preview-document
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pull-requests: write
jobs: 
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dodo CLI
        run: |
          npm install -g @dodo-cli/cli
      - name: Preview docs
        id: preview
        continue-on-error: true
        run: |
          dodo preview --format json 1> stdout.txt 2> stderr.txt
          STATUS=$(jq -r .status stdout.txt 2>/dev/null || echo "false")
          URL=$(jq -r .document_url stdout.txt 2>/dev/null)
      
          if [ "$STATUS" = "false" ] || [ -z "$URL" ]; then
            echo "❌ Document preview failed" >> "body.txt"
            echo "<details><summary>Error Message</summary>" >> "body.txt"
            cat stderr.txt >> "body.txt"
            echo "</details>" >> "body.txt"

            echo "status="failed >> $GITHUB_OUTPUT"
            exit 1
          fi
          echo "✅ Document preview is available [here]($URL)" >> "body.txt"
        env:
          DODO_API_KEY: ${{ secrets.DODO_ACCESS_KEY }}
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: body.txt
      - name: Fail if preview failed
        if: steps.preview.outputs.status == 'failed'
        run: exit 1
