# This workflow is based on the following document
# https://github.com/golangci/golangci-lint-action

name: pull_request
run-name: Golang Lint and Test
on: pull_request

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.55.2
          args: --timeout=10m src 
      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test ./src