# This workflow combines release and publish-docs workflows
name: release-and-publish
on:
  push:
    branches:
      - main
    paths:
      - 'version.txt'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Git
        run : |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "toritorineko29@gmail.com"
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Set tag
        id: tag
        run: |
          VERSION=$(cat version.txt)
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: release
    if: ${{ always() && (needs.release.result == 'success' || needs.release.result == 'skipped') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org' # Important to publish packages. Refer https://github.com/actions/setup-node/
      - name: Download binaries
        run: |
          curl -sL https://github.com/mkei29/dodo-cli/releases/download/0.0.12/dodo-cli_Linux_x86_64.tar.gz | tar xz
          chmod +x dodo-cli
          mv dodo-cli packages/cli-linux-x86-64

          curl -sL https://github.com/mkei29/dodo-cli/releases/download/0.0.12/dodo-cli_Linux_arm64.tar.gz | tar xz
          chmod +x dodo-cli
          mv dodo-cli packages/cli-linux-arm64

          curl -sL https://github.com/mkei29/dodo-cli/releases/download/0.0.12/dodo-cli_Darwin_x86_64.tar.gz | tar xz
          chmod +x dodo-cli
          mv dodo-cli packages/cli-darwin-x86-64

          curl -sL https://github.com/mkei29/dodo-cli/releases/download/0.0.12/dodo-cli_Darwin_arm64.tar.gz | tar xz
          chmod +x dodo-cli
          mv dodo-cli packages/cli-darwin-arm64
      - name: Publish packages
        run: |
          for package in ./packages/*; do
            echo "Publishing $package"
            npm publish $package --tag=latest --access=public
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Install dodo CLI
        run: |
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
