name: upload-document
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs: 
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Install dodo CLI
        run: |
          npm install -g @dodo-doc/cli
      - name: Publish docs
        run: |
          dodo upload
        env:
          DODO_API_KEY: ${{ secrets.DODO_ACCESS_KEY }}
