name: upload-document
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs: 
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dodo CLI
        run: |
          curl -sL https://github.com/mkei29/dodo-cli/releases/download/0.0.12/dodo-cli_Linux_x86_64.tar.gz | tar xz
          chmod +x dodo-cli
      - name: Publish docs
        run: |
          ./dodo-cli upload
        env:
          DODO_API_KEY: ${{ secrets.DODO_ACCESS_KEY }}
