name: upload-document
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs: 
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dodo CLI
        run: |
          npm install -g @dodo-cli/cli
      - name: Publish docs
        run: |
          dodo upload
        env:
          DODO_API_KEY: ${{ secrets.DODO_ACCESS_KEY }}
