// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// Defines values for StatusError.
const (
	Error StatusError = "error"
)

// Defines values for StatusOk.
const (
	Ok StatusOk = "ok"
)

// AssetGetResponseError defines model for asset_get_response_error.
type AssetGetResponseError struct {
	Message string      `json:"message"`
	Status  StatusError `json:"status"`
}

// DocumentGetResponse defines model for document_get_response.
type DocumentGetResponse struct {
	AllowedOrgs []string               `json:"allowed_orgs"`
	IsPublic    bool                   `json:"is_public"`
	Markdown    *string                `json:"markdown,omitempty"`
	Message     string                 `json:"message"`
	Page        map[string]interface{} `json:"page"`
	Status      StatusOk               `json:"status"`
}

// DocumentGetResponseError defines model for document_get_response_error.
type DocumentGetResponseError struct {
	Message string      `json:"message"`
	Status  StatusError `json:"status"`
}

// ErrorResponse defines model for error_response.
type ErrorResponse struct {
	// Message Error message describing the issue
	Message string      `json:"message"`
	Status  StatusError `json:"status"`
}

// LayoutGetResponse defines model for layout_get_response.
type LayoutGetResponse struct {
	AllowedOrgs []string               `json:"allowed_orgs"`
	IsPublic    bool                   `json:"is_public"`
	Layout      map[string]interface{} `json:"layout"`
	Message     string                 `json:"message"`
	ProjectId   string                 `json:"project_id"`
	Status      StatusOk               `json:"status"`
}

// LayoutGetResponseError defines model for layout_get_response_error.
type LayoutGetResponseError struct {
	Message string      `json:"message"`
	Status  StatusError `json:"status"`
}

// Project defines model for project.
type Project struct {
	// BaseUrl Base URL of the project
	BaseUrl string `json:"base_url"`

	// IsPublic Whether the project is public or private
	IsPublic bool `json:"is_public"`

	// OrganizationId ID of the organization the project belongs to
	OrganizationId string `json:"organization_id"`

	// ProjectId ID of the project
	ProjectId string `json:"project_id"`

	// ProjectName Name of the project
	ProjectName string `json:"project_name"`

	// Slug Name of the project
	Slug string `json:"slug"`
}

// ProjectsGetResponse defines model for projects_get_response.
type ProjectsGetResponse struct {
	Message  string    `json:"message"`
	Projects []Project `json:"projects"`
	Status   StatusOk  `json:"status"`
}

// SearchPostRequest defines model for search_post_request.
type SearchPostRequest struct {
	Projects []string `json:"projects"`
	Query    string   `json:"query"`
}

// SearchPostResponse defines model for search_post_response.
type SearchPostResponse struct {
	Message string         `json:"message"`
	Records []SearchRecord `json:"records"`
	Status  StatusOk       `json:"status"`
}

// SearchPostResponseError defines model for search_post_response_error.
type SearchPostResponseError struct {
	Message string      `json:"message"`
	Status  StatusError `json:"status"`
}

// SearchRecord defines model for search_record.
type SearchRecord struct {
	Contents    string `json:"contents"`
	Id          string `json:"id"`
	ProjectId   string `json:"project_id"`
	ProjectSlug string `json:"project_slug"`
	Title       string `json:"title"`
	Url         string `json:"url"`
}

// StatusError defines model for status_error.
type StatusError string

// StatusOk defines model for status_ok.
type StatusOk string

// AssetGetParams defines parameters for AssetGet.
type AssetGetParams struct {
	Demo *string `form:"demo,omitempty" json:"demo,omitempty"`
}

// DocumentGetParams defines parameters for DocumentGet.
type DocumentGetParams struct {
	Demo *string `form:"demo,omitempty" json:"demo,omitempty"`

	// Format Response format, either 'json' or 'html'. Default is 'json'.
	Format *string `form:"format,omitempty" json:"format,omitempty"`
}

// LayoutGetParams defines parameters for LayoutGet.
type LayoutGetParams struct {
	// Demo If true, returns a demo response
	Demo *string `form:"demo,omitempty" json:"demo,omitempty"`
}

// SearchContentsJSONRequestBody defines body for SearchContents for application/json ContentType.
type SearchContentsJSONRequestBody = SearchPostRequest
